services:
  - type: web
    name: mental-health-tracker-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mental-health-db
          property: connectionString

  - type: static
    name: mental-health-tracker-frontend
    buildCommand: echo "Static site build complete"
    staticPublishPath: frontend/pages
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
